[tool.poetry]
name = "cdn"
version = "0.1.0"
description = ""
authors = ["BOJIT <35117353+BOJIT@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pillow = "^10.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
